"""D5 κ-v1 self-critic trainer — Qwen3-30B base as distillation reviewer.

Replaces the cold-start critique used in train_kappa_v1.py (which was a quality
compromise) with REAL critique generated by Qwen3-30B base model itself, given
the source paper as privileged info. This tests two hypotheses simultaneously:

1. Does SDPO at the distillation stage produce positive learning signal when
   given REAL reviewer feedback (not cold-start)?
2. Can a 30B open-source model self-review its own distillations approaching the
   quality of an Opus reviewer? (Reframe per user 2026-04-27.)

Architecture (per RETRIEVAL_DESIGN_v1 + reframe):
- Per iter, per instance i ∈ 1..8, per round j ∈ 1..3:
    Teacher prompt = goal + oracle_batch_j + critique_{i,j-1}*  (* round 1 cold-start)
    Student prompt = goal + oracle_batch_j  (no critique)
    Sample teacher distillation A_i^j; compute student logprobs on same tokens
    Build SDPO datum
  - After each A_i^j: dispatch self-critic via base sampling_client + source_paper.md
    parse XML → critique_{i,j} (used as next round's teacher critique input)
  - Per-instance critique chain (round 2 critique = critic on A_i^1)

After 3 rounds: plan generation per instance using build_kappa_plan_prompt(v4)

Key differences from train_kappa_v1.py:
- DROPS DISTILLATION_COLD_START_CRITIQUE for round 2/3 (only round 1 cold-start)
- ADDS sampling_client_base for self-critic (Qwen3-30B base, frozen)
- Per-instance critique chain (NOT shared across instances)

Cost: $0 critic (Tinker) + ~$24 audit (3 iters × 8 plan audits via Opus subagent)

Usage:
    PYTHONPATH=src python -m co_scientist.d5_abstract_retrieve_refine.train_kappa_v1_self \
        log_path=projects/d5_abstract_retrieve_refine/runs/2026_04_28_kappa_v1_self_smoke
"""
from __future__ import annotations

import json
import logging
import sys
import time
from pathlib import Path

import numpy as np

SRC_ROOT = Path(__file__).resolve().parents[2]
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

import chz
import tinker
from tinker import types
from tinker_cookbook import checkpoint_utils, model_info, renderers
from tinker_cookbook.tokenizer_utils import get_tokenizer
from tinker_cookbook.utils import ml_log

from co_scientist.shared.api_profiles import create_service_client
from co_scientist.d5_abstract_retrieve_refine.kappa_prompts_v1 import (
    DISTILLATION_COLD_START_CRITIQUE,
    build_distillation_student_prompt,
    build_distillation_teacher_prompt,
    build_kappa_plan_prompt,
    build_sdpo_datum,
    build_self_review_critic_prompt,
    extract_distillation,
    parse_distillation_critique_xml,
)
from co_scientist.d5_abstract_retrieve_refine.oracle_batch_helper_v1 import (
    ORACLE_V2_DEFAULT_PATH,
    make_batches,
    parse_oracle,
    render_batch,
)

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logging.getLogger("httpx").setLevel(logging.WARN)


REPO_ROOT = Path(__file__).resolve().parents[3]


@chz.chz
class Config:
    api_profile: str | None = "new"
    base_url: str | None = None

    log_path: str = "projects/d5_abstract_retrieve_refine/runs/2026_04_28_kappa_v1_self_smoke"
    goal_path: str = "projects/d5_abstract_retrieve_refine/dataset/research_goal.txt"
    oracle_path: str = ORACLE_V2_DEFAULT_PATH  # medium.md
    source_paper_path: str = "projects/d5_abstract_retrieve_refine/data/source_paper/v2.md"

    model_name: str = "Qwen/Qwen3-30B-A3B"
    lora_rank: int = 64
    learning_rate: float = 5e-5

    n_instances: int = 8
    n_rounds: int = 3
    batch_sizes: tuple[int, ...] = (60, 60, 61)
    shuffle_seed: int = 43

    distillation_max_tokens: int = 3500
    plan_max_tokens: int = 4096
    critic_max_tokens: int = 1500  # XML output ≤ ~1.5K tokens

    plan_prompt_version: str = "v4"

    sdpo_scale: float = 1.0
    sdpo_clip_advantage: float = 5.0

    n_iter: int = 3  # quality-first: 3 iter for cleaner trajectory
    save_every: int = 1
    n_grad_steps_per_iter: int = 4

    today_date: str = "2026_04_28"
    temperature: float = 1.0
    top_p: float = 0.95


def _resolve(p: str) -> Path:
    return (REPO_ROOT / p).resolve()


def _safe_pos_frac(advs):
    if not advs:
        return 0.0
    return float(np.mean([1.0 if a > 0 else 0.0 for a in advs]))


def _safe_mean_abs(advs):
    if not advs:
        return 0.0
    return float(np.mean([abs(a) for a in advs]))


def main(config: Config):
    log_dir = _resolve(config.log_path)
    log_dir.mkdir(parents=True, exist_ok=True)
    ml_log.setup_logging(
        log_dir=str(log_dir),
        wandb_project=None,
        wandb_name=None,
        config=config,
        do_configure_logging_module=True,
    )

    # Inputs
    goal = _resolve(config.goal_path).read_text().strip()
    source_paper = _resolve(config.source_paper_path).read_text().strip()
    oracle_items = parse_oracle(_resolve(config.oracle_path))
    batches = make_batches(oracle_items, sizes=config.batch_sizes,
                            seed=config.shuffle_seed)
    logger.info("Inputs loaded: goal=%d chars, source_paper=%d chars, oracle=%d items in %s",
                len(goal), len(source_paper), len(oracle_items), [len(b) for b in batches])

    # Save config snapshot
    cfg_dump = {k: getattr(config, k) for k in dir(config)
                if not k.startswith("_") and not callable(getattr(config, k))}
    (log_dir / "config.json").write_text(json.dumps(cfg_dump, default=str, indent=2))

    # Tokenizer + renderer
    tokenizer = get_tokenizer(config.model_name)
    renderer_name = model_info.get_recommended_renderer_name(config.model_name)
    renderer = renderers.get_renderer(renderer_name, tokenizer)

    # Tinker service + LoRA training client
    service_client = create_service_client(
        base_url=config.base_url, api_profile=config.api_profile,
    )
    last_checkpoint = checkpoint_utils.get_last_checkpoint(str(log_dir))
    if last_checkpoint is not None:
        training_client = service_client.create_training_client_from_state_with_optimizer(
            last_checkpoint["state_path"]
        )
        start_iter = last_checkpoint.get("batch", 0) + 1
        logger.info("Resuming from iter %d", start_iter)
    else:
        training_client = service_client.create_lora_training_client(
            base_model=config.model_name, rank=config.lora_rank,
        )
        start_iter = 0
        logger.info("Fresh LoRA training client (rank=%d)", config.lora_rank)

    adam_params = types.AdamParams(
        learning_rate=config.learning_rate, beta1=0.9, beta2=0.95, eps=1e-8,
    )

    distill_sampling_params = tinker.types.SamplingParams(
        max_tokens=config.distillation_max_tokens,
        temperature=config.temperature,
        top_p=config.top_p,
        stop=renderer.get_stop_sequences(),
    )
    plan_sampling_params = tinker.types.SamplingParams(
        max_tokens=config.plan_max_tokens,
        temperature=config.temperature,
        top_p=config.top_p,
        stop=renderer.get_stop_sequences(),
    )
    critic_sampling_params = tinker.types.SamplingParams(
        max_tokens=config.critic_max_tokens,
        temperature=config.temperature,
        top_p=config.top_p,
        stop=renderer.get_stop_sequences(),
    )

    # Self-critic uses BASE Qwen3-30B (frozen, never updated)
    base_sampling_client = service_client.create_sampling_client(base_model=config.model_name)

    # Output files
    metrics_path = log_dir / "metrics.jsonl"
    checkpoints_path = log_dir / "checkpoints.jsonl"
    eval_rollouts_path = log_dir / "eval_rollouts.jsonl"
    critic_log_path = log_dir / "critic_log.jsonl"

    # ===========================================================================
    # Main loop
    # ===========================================================================
    for iter_idx in range(start_iter, config.n_iter):
        t0 = time.time()

        # Periodic checkpoint
        if config.save_every > 0 and iter_idx % config.save_every == 0 and iter_idx > 0:
            checkpoint_utils.save_checkpoint(
                training_client=training_client,
                name=f"{iter_idx:06d}_{config.today_date}",
                log_path=str(log_dir),
                kind="state",
                loop_state={"batch": iter_idx},
            )

        # Sampling client = current LoRA weights (for distillation samples)
        sp_path = training_client.save_weights_for_sampler(
            name=f"iter_{iter_idx:04d}"
        ).result().path
        sampling_client = service_client.create_sampling_client(model_path=sp_path)
        with open(checkpoints_path, "a") as f:
            f.write(json.dumps({"iter": iter_idx, "sampler_path": sp_path,
                                 "ts": time.strftime("%Y-%m-%d %H:%M:%S")}) + "\n")

        # ===== Per-instance loop (sequential due to per-instance critique chain) =====
        all_datums = []
        all_advs = []
        distillations_per_instance: list[list[str]] = [[] for _ in range(config.n_instances)]
        critique_failures = 0

        t_iter_inner0 = time.time()
        for inst_idx in range(config.n_instances):
            prev_critique = DISTILLATION_COLD_START_CRITIQUE  # round 1 cold-start

            for round_idx in range(1, config.n_rounds + 1):
                batch = batches[round_idx - 1]
                batch_text = render_batch(batch)

                # ----- Distillation: teacher + student -----
                teacher_text = build_distillation_teacher_prompt(
                    goal=goal, oracle_batch_text=batch_text,
                    critique_xml=prev_critique, round_idx=round_idx,
                )
                student_text = build_distillation_student_prompt(
                    goal=goal, oracle_batch_text=batch_text, round_idx=round_idx,
                )
                teacher_input = renderer.build_generation_prompt(
                    [{"role": "user", "content": teacher_text}]
                )
                student_input = renderer.build_generation_prompt(
                    [{"role": "user", "content": student_text}]
                )
                student_tokens = student_input.to_ints()

                teacher_result = sampling_client.sample(
                    prompt=teacher_input, num_samples=1,
                    sampling_params=distill_sampling_params,
                ).result()
                seq = teacher_result.sequences[0]

                full_s_lp = sampling_client.compute_logprobs(
                    types.ModelInput.from_ints(tokens=student_tokens + list(seq.tokens))
                ).result()

                gen = list(seq.tokens)
                t_lp_seq = list(seq.logprobs) if seq.logprobs else []
                s_lp = list(full_s_lp[len(student_tokens):len(student_tokens) + len(gen)])
                if not gen or len(t_lp_seq) != len(gen) or len(s_lp) != len(gen):
                    logger.warning("Iter %d inst %d round %d: len mismatch; skipping",
                                   iter_idx, inst_idx, round_idx)
                    distillations_per_instance[inst_idx].append("")
                    continue

                per_tok_adv = []
                for t_, s_ in zip(t_lp_seq, s_lp):
                    a = float(t_ - s_) * config.sdpo_scale
                    a = max(-config.sdpo_clip_advantage,
                              min(config.sdpo_clip_advantage, a))
                    per_tok_adv.append(a)
                all_advs.extend(per_tok_adv)
                datum = build_sdpo_datum(
                    student_prompt_tokens=student_tokens,
                    gen_tokens=gen,
                    student_logprobs=s_lp,
                    advantages=per_tok_adv,
                )
                all_datums.append(datum)

                A_text = extract_distillation(tokenizer.decode(gen))
                distillations_per_instance[inst_idx].append(A_text)

                # ----- Self-critic via base Qwen3-30B (skip after final round) -----
                if round_idx < config.n_rounds:
                    critic_prompt = build_self_review_critic_prompt(
                        goal=goal, distillation_text=A_text,
                        source_paper=source_paper, round_idx=round_idx,
                    )
                    critic_input = renderer.build_generation_prompt(
                        [{"role": "user", "content": critic_prompt}]
                    )
                    t_crit0 = time.time()
                    critic_result = base_sampling_client.sample(
                        prompt=critic_input, num_samples=1,
                        sampling_params=critic_sampling_params,
                    ).result()
                    critic_raw = tokenizer.decode(critic_result.sequences[0].tokens)
                    parsed_critique = parse_distillation_critique_xml(critic_raw)
                    if parsed_critique == DISTILLATION_COLD_START_CRITIQUE:
                        critique_failures += 1
                    prev_critique = parsed_critique
                    t_crit = time.time() - t_crit0
                    with open(critic_log_path, "a") as f:
                        f.write(json.dumps({
                            "iter": iter_idx, "inst_idx": inst_idx, "round_idx": round_idx,
                            "critic_prompt_chars": len(critic_prompt),
                            "critic_raw_chars": len(critic_raw),
                            "parsed_critique_chars": len(parsed_critique),
                            "parse_succeeded": parsed_critique != DISTILLATION_COLD_START_CRITIQUE,
                            "wall_sec": t_crit,
                            "ts": time.strftime("%Y-%m-%d %H:%M:%S"),
                        }) + "\n")

        t_iter_inner = time.time() - t_iter_inner0
        logger.info("Iter %d: per-instance loop done in %.1fs (%d datums, %d critique failures / %d)",
                    iter_idx, t_iter_inner, len(all_datums), critique_failures,
                    config.n_instances * (config.n_rounds - 1))

        # ===== TRAIN STEP =====
        t_step0 = time.time()
        if all_datums:
            n_steps = max(1, config.n_grad_steps_per_iter)
            chunk_size = max(1, len(all_datums) // n_steps)
            chunks = [all_datums[i:i + chunk_size]
                      for i in range(0, len(all_datums), chunk_size)]
            for chunk in chunks[:n_steps]:
                if not chunk:
                    continue
                fb_fut = training_client.forward_backward(chunk, loss_fn="importance_sampling")
                os_fut = training_client.optim_step(adam_params)
                fb_fut.result()
                os_fut.result()
        t_step = time.time() - t_step0

        mean_adv = float(np.mean(all_advs)) if all_advs else 0.0
        pos_frac = _safe_pos_frac(all_advs)
        mean_abs = _safe_mean_abs(all_advs)
        logger.info("Iter %d SDPO: %d datums, mean_adv=%.4f, pos_frac=%.3f, train=%.1fs",
                    iter_idx, len(all_datums), mean_adv, pos_frac, t_step)

        # ===== PLAN GENERATION (post-train sampler) =====
        sp_path_post = training_client.save_weights_for_sampler(
            name=f"iter_{iter_idx:04d}_post"
        ).result().path
        sampling_client_post = service_client.create_sampling_client(model_path=sp_path_post)

        plan_records = []
        for k in range(config.n_instances):
            A_list = distillations_per_instance[k]
            while len(A_list) < config.n_rounds:
                A_list.append("")
            plan_prompt = build_kappa_plan_prompt(
                goal=goal, A_list=A_list, version=config.plan_prompt_version,
            )
            plan_input = renderer.build_generation_prompt(
                [{"role": "user", "content": plan_prompt}]
            )
            plan_result = sampling_client_post.sample(
                prompt=plan_input, num_samples=1, sampling_params=plan_sampling_params,
            ).result()
            plan_seq = plan_result.sequences[0]
            plan_text = tokenizer.decode(plan_seq.tokens)
            plan_records.append({
                "iter": iter_idx,
                "plan_id": f"iter_{iter_idx:03d}_inst_{k}",
                "instance_idx": k,
                "text": plan_text,
                "stop_reason": plan_seq.stop_reason,
                "n_tokens": len(plan_seq.tokens),
            })

        with open(eval_rollouts_path, "a") as f:
            for rec in plan_records:
                f.write(json.dumps(rec) + "\n")

        # ===== METRICS =====
        with open(metrics_path, "a") as f:
            f.write(json.dumps({
                "iter": iter_idx,
                "n_datums": len(all_datums),
                "n_adv_tokens": len(all_advs),
                "mean_adv": mean_adv,
                "pos_frac": pos_frac,
                "mean_abs_adv": mean_abs,
                "critique_failures": critique_failures,
                "n_critic_calls": config.n_instances * (config.n_rounds - 1),
                "wall_total_sec": time.time() - t0,
                "wall_inner_sec": t_iter_inner,
                "wall_train_sec": t_step,
                "ts": time.strftime("%Y-%m-%d %H:%M:%S"),
                "n_plans": len(plan_records),
                "post_train_sampler": sp_path_post,
            }) + "\n")

        logger.info("Iter %d done in %.1fs", iter_idx, time.time() - t0)

    # Final checkpoint
    checkpoint_utils.save_checkpoint(
        training_client=training_client,
        name=f"final_{config.today_date}",
        log_path=str(log_dir),
        kind="both",
        loop_state={"batch": config.n_iter},
    )
    logger.info("κ-self smoke run complete: %d iter", config.n_iter)


if __name__ == "__main__":
    config = chz.entrypoint(Config)
    main(config)
