"""D5 Phase 3 τ baseline — frozen Qwen3-30B-A3B + 3-round distillation pipeline.

Phase 3 (走线 A, Path Y) baseline run: NO training, NO LoRA, NO critic.
8 plans, each generated by:
  1. Round 1: model(goal + oracle_batch_1) → A_1 (~700 tokens distilled list)
  2. Round 2: model(goal + oracle_batch_2) → A_2 (independent of A_1)
  3. Round 3: model(goal + oracle_batch_3) → A_3 (independent of A_1, A_2)
  4. PLAN: model(goal + [A_1, A_2, A_3]) → research plan

Implements σ analog with retrieval-distillation pipeline replacing Opus-curated
slim oracle. Question Phase 3 answers (with κ later): does dynamic distillation
beat Opus's hand-pick on the same medium oracle pool?

Outputs `buffer.jsonl` with one row per plan, including all 3 distillations.
Subsequent audit (audit_v3_isolated.py on the 8 plan_text fields) → Gate 1 verdict.

Usage:
    PYTHONPATH=src python -m co_scientist.d5_abstract_retrieve_refine.train_tau_v1 \
        log_path=projects/d5_abstract_retrieve_refine/runs/2026_04_28_tau_v1
"""
from __future__ import annotations

import json
import logging
import sys
import time
from pathlib import Path

import chz
import tinker
from tinker_cookbook import model_info, renderers
from tinker_cookbook.tokenizer_utils import get_tokenizer

SRC_ROOT = Path(__file__).resolve().parents[2]
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from co_scientist.shared.api_profiles import create_service_client
from co_scientist.d5_abstract_retrieve_refine.kappa_prompts_v1 import (
    build_distillation_student_prompt,
    build_kappa_plan_prompt,
    extract_distillation,
)
from co_scientist.d5_abstract_retrieve_refine.oracle_batch_helper_v1 import (
    ORACLE_V2_DEFAULT_PATH,
    make_batches,
    parse_oracle,
    render_batch,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[3]


@chz.chz
class Config:
    api_profile: str | None = "new"
    base_url: str | None = None

    log_path: str = "projects/d5_abstract_retrieve_refine/runs/2026_04_28_tau_v1"

    goal_path: str = "projects/d5_abstract_retrieve_refine/dataset/research_goal.txt"
    oracle_path: str = ORACLE_V2_DEFAULT_PATH  # medium.md per Q3 reframe

    model: str = "Qwen/Qwen3-30B-A3B"

    num_plans: int = 8                      # Q-locked: 8 plans (matches σ batch size)
    n_rounds: int = 3                       # Q4.1 lock
    batch_sizes: tuple[int, ...] = (60, 60, 61)  # Q4.1 lock; sums to 181 (medium total)
    shuffle_seed: int = 42                  # Q4.1 τ_seed (κ uses 43)

    distillation_max_tokens: int = 3500     # τ_v2 (2026-04-27): 1024 → 3500 to fit Qwen3 thinking (~500-1000 tok) + actual distillation (~1500-2000 tok). 1024 caused A_1 to be 100% thinking with 0 distillation in τ_v1 (gate1 STOP at 18.12).
    plan_max_tokens: int = 4096             # Q6.1 same as μ-v4

    # τ_v4 (2026-04-27): plan prompt version selector. "v3" = original Q4.3
    # plan footer; "v4" = adds T2/T3 disentanglement + compute instructions
    # that the oracle cannot supply.
    plan_prompt_version: str = "v3"

    temperature: float = 1.0
    top_p: float = 0.95


def main(config: Config):
    log_dir = (REPO_ROOT / config.log_path).resolve()
    log_dir.mkdir(parents=True, exist_ok=True)

    goal = (REPO_ROOT / config.goal_path).resolve().read_text().strip()
    oracle_items = parse_oracle((REPO_ROOT / config.oracle_path).resolve())
    if sum(config.batch_sizes) != len(oracle_items):
        logger.warning("batch_sizes sum=%d != oracle items=%d", sum(config.batch_sizes), len(oracle_items))
    batches = make_batches(oracle_items, sizes=config.batch_sizes, seed=config.shuffle_seed)
    logger.info("Oracle: %d items split into %s batches (seed=%d)",
                len(oracle_items), [len(b) for b in batches], config.shuffle_seed)

    tokenizer = get_tokenizer(config.model)
    renderer_name = model_info.get_recommended_renderer_name(config.model)
    renderer = renderers.get_renderer(renderer_name, tokenizer)

    service_client = create_service_client(api_profile=config.api_profile, base_url=config.base_url)
    sampling_client = service_client.create_sampling_client(base_model=config.model)

    distill_params = tinker.types.SamplingParams(
        max_tokens=config.distillation_max_tokens,
        temperature=config.temperature,
        top_p=config.top_p,
        stop=renderer.get_stop_sequences(),
    )
    plan_params = tinker.types.SamplingParams(
        max_tokens=config.plan_max_tokens,
        temperature=config.temperature,
        top_p=config.top_p,
        stop=renderer.get_stop_sequences(),
    )

    config_dump = {
        "variant": "tau",
        "model": config.model,
        "num_plans": config.num_plans,
        "n_rounds": config.n_rounds,
        "batch_sizes": list(config.batch_sizes),
        "shuffle_seed": config.shuffle_seed,
        "distillation_max_tokens": config.distillation_max_tokens,
        "plan_max_tokens": config.plan_max_tokens,
        "temperature": config.temperature,
        "top_p": config.top_p,
        "oracle_path": str(config.oracle_path),
        "goal_path": str(config.goal_path),
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
    }
    (log_dir / "config_tau.json").write_text(json.dumps(config_dump, indent=2))

    # =========================================================================
    # Stage 1: Distillation rounds (3 rounds × num_samples=num_plans, INDEPENDENT)
    # =========================================================================
    distillations_per_plan: list[list[str]] = [[] for _ in range(config.num_plans)]
    raw_distillation_outputs: list[list[str]] = [[] for _ in range(config.num_plans)]

    for round_idx in range(1, config.n_rounds + 1):
        batch = batches[round_idx - 1]
        oracle_batch_text = render_batch(batch)
        distill_prompt = build_distillation_student_prompt(
            goal=goal, oracle_batch_text=oracle_batch_text, round_idx=round_idx
        )
        logger.info("Round %d: %d items, prompt %d chars (~%d tokens)",
                    round_idx, len(batch), len(distill_prompt), len(distill_prompt)//4)

        convo = [{"role": "user", "content": distill_prompt}]
        model_input = renderer.build_generation_prompt(convo)
        result = sampling_client.sample(
            prompt=model_input,
            num_samples=config.num_plans,
            sampling_params=distill_params,
        ).result()

        for plan_idx, seq in enumerate(result.sequences):
            raw_text = tokenizer.decode(seq.tokens)
            extracted = extract_distillation(raw_text)
            distillations_per_plan[plan_idx].append(extracted)
            raw_distillation_outputs[plan_idx].append(raw_text)
            logger.info("  plan_%d round_%d: raw=%d chars, extracted=%d chars (think stripped: %s)",
                        plan_idx, round_idx, len(raw_text), len(extracted),
                        len(extracted) < len(raw_text))

    # =========================================================================
    # Stage 2: Plan generation (per-plan, sees own [A_1, A_2, A_3] concat)
    # =========================================================================
    buffer_path = log_dir / "buffer.jsonl"
    with open(buffer_path, "a") as f:
        for plan_idx in range(config.num_plans):
            A_list = distillations_per_plan[plan_idx]
            plan_prompt = build_kappa_plan_prompt(goal, A_list, version=config.plan_prompt_version)
            logger.info("Plan %d: prompt %d chars (~%d tokens)",
                        plan_idx, len(plan_prompt), len(plan_prompt)//4)

            convo = [{"role": "user", "content": plan_prompt}]
            model_input = renderer.build_generation_prompt(convo)
            result = sampling_client.sample(
                prompt=model_input,
                num_samples=1,
                sampling_params=plan_params,
            ).result()

            seq = result.sequences[0]
            raw_plan_text = tokenizer.decode(seq.tokens)

            f.write(json.dumps({
                "variant": "tau",
                "sample_idx": plan_idx,
                "plan_text": raw_plan_text,            # full raw — audit_v3 reads this then strips
                "distillations": A_list,                # 3 extracted distillations per plan
                "raw_distillations": raw_distillation_outputs[plan_idx],  # debug
                "stop_reason": seq.stop_reason,
                "model": config.model,
                "n_rounds": config.n_rounds,
                "shuffle_seed": config.shuffle_seed,
                "plan_char_len": len(raw_plan_text),
            }) + "\n")
            logger.info("  plan_%d wrote: plan=%d chars",
                        plan_idx, len(raw_plan_text))

    logger.info("τ baseline run complete: %d plans → %s", config.num_plans, buffer_path)


if __name__ == "__main__":
    main(chz.entrypoint(Config))
