"""D5 α baseline — naive Opus distillation.

Tests: does Qwen3-30B-A3B LoRA SFT on N Opus-generated plans beat μ baseline
(8.88/20)? If α ≥ μ, plan-level SDPO + critic adds nothing over plain
distillation. This is the "anti-distillation" reviewer attack.

SFT data source: `projects/d5_abstract_retrieve_refine/data/plans/opus_v1.jsonl`
(N entries; each `{plan_text: str, condition: "with_paper"|"no_paper"}`).
Generated by `generate_opus_plans_v1` subagent BEFORE running this trainer.

NO oracle abstraction in eval/training prompts (α just trains on the goal
→ plan target, same as a vanilla distillation setup).

Usage:
    PYTHONPATH=src python -m co_scientist.d5_abstract_retrieve_refine.train_alpha_baseline_v1 \
        log_path=projects/d5_abstract_retrieve_refine/runs/2026_04_25_alpha_baseline_v1 \
        n_epochs=5 eval_every=1

Decision rule (post-run):
- α ≥ μ (8.88) → "distillation is enough, plan-level SDPO redundant"
- α < μ → SDPO has value beyond direct distillation
"""
from __future__ import annotations

import json
import logging
import sys
import time
from pathlib import Path

import numpy as np

SRC_ROOT = Path(__file__).resolve().parents[2]
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

import chz
import tinker
import torch
from tinker import types
from tinker.types.tensor_data import TensorData
from tinker_cookbook import checkpoint_utils, model_info, renderers
from tinker_cookbook.tokenizer_utils import get_tokenizer
from tinker_cookbook.utils import ml_log

from co_scientist.shared.api_profiles import create_service_client
from co_scientist.shared.opus_audit_subagent import OpusAuditClient
from co_scientist.d5_abstract_retrieve_refine.mu_prompts_v1 import (
    build_audit_request_payload,
    extract_solution,
)
from co_scientist.d5_abstract_retrieve_refine.train_beta_baseline_v1 import (
    build_student_prompt,
    _decode_plan,
)

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logging.getLogger("httpx").setLevel(logging.WARN)


REPO_ROOT = Path(__file__).resolve().parents[3]


@chz.chz
class Config:
    api_profile: str | None = "new"
    base_url: str | None = None

    log_path: str = (
        "projects/d5_abstract_retrieve_refine/runs/2026_04_25_alpha_baseline_v1"
    )
    goal_path: str = "projects/d5_abstract_retrieve_refine/dataset/research_goal.txt"
    opus_plans_path: str = (
        "projects/d5_abstract_retrieve_refine/data/plans/opus_v1.jsonl"
    )

    model_name: str = "Qwen/Qwen3-30B-A3B"
    lora_rank: int = 64
    learning_rate: float = 1e-5

    # SFT loop: each "iter" walks the dataset once (1 datum per Opus plan)
    n_epochs: int = 5

    # Sampling for eval
    n_eval_plans: int = 8
    max_tokens: int = 2048
    temperature: float = 1.0
    top_p: float = 0.95
    eval_every: int = 1  # eval after every epoch

    save_every: int = 2
    today_date: str = "2026_04_25"

    sft_weight: float = 1.0


def _resolve(p: str) -> Path:
    return (REPO_ROOT / p).resolve()


def _build_sft_datum(goal: str, opus_plan_text: str, renderer, tokenizer, sft_weight: float):
    """Build one SFT datum from (goal → opus_plan) using renderer's supervised builder."""
    student_text = build_student_prompt(goal)
    target_text = f"<solution>\n{opus_plan_text}\n</solution>"
    convo = [
        {"role": "user", "content": student_text},
        {"role": "assistant", "content": target_text},
    ]
    sup_input, sup_weights = renderer.build_supervised_example(convo)
    full_seq = sup_input.to_ints()
    weights = sup_weights.tolist() if hasattr(sup_weights, "tolist") else list(sup_weights)
    advantages = [sft_weight * float(w) for w in weights[1:]]
    logprobs = [0.0] * (len(full_seq) - 1)
    return types.Datum(
        model_input=types.ModelInput.from_ints(tokens=full_seq[:-1]),
        loss_fn_inputs={
            "target_tokens": TensorData.from_torch(
                torch.tensor(full_seq[1:], dtype=torch.long)
            ),
            "logprobs": TensorData.from_torch(
                torch.tensor(logprobs, dtype=torch.float)
            ),
            "advantages": TensorData.from_torch(
                torch.tensor(advantages, dtype=torch.float)
            ),
        },
    )


def main(config: Config):
    log_dir = _resolve(config.log_path)
    log_dir.mkdir(parents=True, exist_ok=True)
    ml_log.setup_logging(
        log_dir=str(log_dir), wandb_project=None, wandb_name=None,
        config=config, do_configure_logging_module=True,
    )

    goal = _resolve(config.goal_path).read_text().strip()
    plans_path = _resolve(config.opus_plans_path)
    assert plans_path.exists(), f"Opus plans not found: {plans_path} — run generate_opus_plans_v1 first"

    opus_plans = []
    with open(plans_path) as f:
        for line in f:
            line = line.strip()
            if not line: continue
            opus_plans.append(json.loads(line))
    assert opus_plans, f"Empty opus plans file: {plans_path}"
    logger.info("α baseline. goal=%d c, %d Opus plans loaded from %s",
                 len(goal), len(opus_plans), plans_path)
    logger.info("log_dir = %s", log_dir)

    cfg_path = log_dir / "config.json"
    cfg_path.write_text(json.dumps({k: getattr(config, k) for k in dir(config)
                                     if not k.startswith("_") and not callable(getattr(config, k))},
                                    default=str, indent=2))

    tokenizer = get_tokenizer(config.model_name)
    renderer_name = model_info.get_recommended_renderer_name(config.model_name)
    renderer = renderers.get_renderer(renderer_name, tokenizer)

    service_client = create_service_client(
        base_url=config.base_url, api_profile=config.api_profile,
    )
    last_ckpt = checkpoint_utils.get_last_checkpoint(str(log_dir))
    if last_ckpt is None:
        training_client = service_client.create_lora_training_client(
            base_model=config.model_name, rank=config.lora_rank,
        )
        start_epoch = 0
    else:
        training_client = service_client.create_training_client_from_state_with_optimizer(
            last_ckpt["state_path"]
        )
        start_epoch = last_ckpt.get("batch", 0) + 1

    adam_params = types.AdamParams(
        learning_rate=config.learning_rate, beta1=0.9, beta2=0.95, eps=1e-8,
    )
    sampling_params = tinker.types.SamplingParams(
        max_tokens=config.max_tokens,
        temperature=config.temperature,
        top_p=config.top_p,
        stop=renderer.get_stop_sequences(),
    )

    audit_client = OpusAuditClient(log_path=log_dir)

    # Build all SFT datums up front (datasets are small, ~16 examples)
    sft_datums = []
    for i, p in enumerate(opus_plans):
        plan_text = p.get("plan_text") or p.get("text") or ""
        if not plan_text.strip():
            logger.warning("Plan %d empty; skipping", i)
            continue
        d = _build_sft_datum(goal, plan_text, renderer, tokenizer, config.sft_weight)
        sft_datums.append(d)
    logger.info("Built %d SFT datums", len(sft_datums))

    # student_input for eval (goal only)
    student_text = build_student_prompt(goal)
    student_input = renderer.build_generation_prompt(
        [{"role": "user", "content": student_text}]
    )

    metrics_path = log_dir / "metrics.jsonl"
    eval_path = log_dir / "eval_rollouts.jsonl"
    checkpoints_path = log_dir / "checkpoints.jsonl"

    for epoch_idx in range(start_epoch, config.n_epochs):
        t0 = time.time()

        if config.save_every > 0 and epoch_idx % config.save_every == 0 and epoch_idx > 0:
            checkpoint_utils.save_checkpoint(
                training_client=training_client,
                name=f"{epoch_idx:06d}_{config.today_date}",
                log_path=str(log_dir),
                kind="state",
                loop_state={"batch": epoch_idx},
            )

        sp_path = training_client.save_weights_for_sampler(
            name=f"epoch_{epoch_idx:04d}"
        ).result().path
        sampling_client = service_client.create_sampling_client(model_path=sp_path)
        with open(checkpoints_path, "a") as f:
            f.write(json.dumps({"epoch": epoch_idx, "sampler_path": sp_path,
                                 "ts": time.strftime("%Y-%m-%d %H:%M:%S")}) + "\n")

        # SFT step: ONE forward_backward over the whole batch
        t_step0 = time.time()
        fb_fut = training_client.forward_backward(sft_datums, loss_fn="importance_sampling")
        os_fut = training_client.optim_step(adam_params)
        fb_fut.result()
        os_fut.result()
        t_step = time.time() - t_step0
        logger.info("Epoch %d: SFT step (%d datums) in %.1fs",
                     epoch_idx, len(sft_datums), t_step)

        # Eval audit
        if epoch_idx % config.eval_every == 0:
            t_eval0 = time.time()
            eval_result = sampling_client.sample(
                prompt=student_input,
                num_samples=config.n_eval_plans,
                sampling_params=sampling_params,
            ).result()
            eval_plans = []
            for k, seq in enumerate(eval_result.sequences):
                pid = f"epoch_{epoch_idx:03d}_eval_{k}"
                ptext = _decode_plan(seq, tokenizer, renderer)
                eval_plans.append({"plan_id": pid, "text": ptext})
            audit_client.submit(
                epoch_idx,
                build_audit_request_payload(iter_idx=epoch_idx, goal=goal, plans=eval_plans),
            )
            with open(eval_path, "a") as f:
                for ep in eval_plans:
                    f.write(json.dumps({"epoch": epoch_idx, **ep}) + "\n")
            logger.info("Epoch %d: eval audit submitted (%d plans, %.1fs sample, async)",
                         epoch_idx, len(eval_plans), time.time() - t_eval0)

        with open(metrics_path, "a") as f:
            f.write(json.dumps({
                "epoch": epoch_idx,
                "n_datums": len(sft_datums),
                "wall_total_sec": time.time() - t0,
                "wall_train_sec": t_step,
                "ts": time.strftime("%Y-%m-%d %H:%M:%S"),
            }) + "\n")
        logger.info("Epoch %d done in %.1fs", epoch_idx, time.time() - t0)

    checkpoint_utils.save_checkpoint(
        training_client=training_client,
        name=f"final_{config.today_date}",
        log_path=str(log_dir),
        kind="both",
        loop_state={"batch": config.n_epochs},
    )

    logger.info("Collecting audit responses (waiting up to 30 min)...")
    audit_summary = audit_client.collect_all(
        out_path=log_dir / "audit_log.jsonl",
        timeout_sec=1800.0, poll_interval_sec=15.0,
    )
    valid = [s for s in audit_summary if s.get("mean_total") is not None]
    if valid:
        last3 = valid[-3:]
        alpha_proxy = float(np.mean([s["mean_total"] for s in last3]))
        logger.info("==================== α PROXY ====================")
        logger.info("α proxy (mean of last %d audit means): %.2f /20", len(last3), alpha_proxy)
        logger.info("μ baseline:    8.88")
        logger.info("δ baseline:    6.75")
        logger.info("ε baseline:   12.13")
        logger.info("If α ≥ 8.88 → distillation is enough, SDPO redundant")
        logger.info("=================================================")
    logger.info("α baseline run complete.")


if __name__ == "__main__":
    config = chz.entrypoint(Config)
    main(config)
