"""D6 OPD-KL-anchor trainer (SCAFFOLD ONLY, DEFERRED) — OPD-grounded + KL anchor toward oracle SFT.

SCAFFOLD ONLY — requires an oracle SFT checkpoint (π_oracle) that does not
yet exist. The full implementation is blocked until:

  1. OPD pilot completes and produces a best checkpoint
  2. oracle SFT is trained on oracle-grounded proposals for this goal
     (separate training run using oracle.jsonl as target text)
  3. oracle SFT checkpoint path is provided via oracle_sft_checkpoint config

Background (D5 finding F18):
  The KL anchor toward π_oracle acts as a stabilizer, not a performance booster.
  It prevents the axis-collapse Goodhart seen in OPD-grounded alone (equation
  score inflates while citation/empirical scores collapse). Mean score across all
  iterations is highest with KL anchor in D5, but peak is unchanged.

  For D6: the oracle SFT would be trained on 30–50 oracle-grounded proposals
  generated by prompting Opus with the reference_proposal.md + oracle abstraction.
  KL beta = 0.01 recommended (D5 found 0.05 causes over-regularization).

Usage (once oracle_sft_checkpoint is available):
    PYTHONPATH=src python -m co_scientist.d6_grant_proposal.train_opd_kl_anchor \\
        goal_domain=ai goal_name=02_foundational_rl \\
        oracle_sft_checkpoint=projects/d6_grant_proposal/data/ai/02_foundational_rl/oracle_sft_v1 \\
        log_path=projects/d6_grant_proposal/runs/2026_05_xx_pilot_foundrl_opd_kl_anchor
"""
from __future__ import annotations


def main():
    raise NotImplementedError(
        "train_opd_kl_anchor requires an oracle SFT checkpoint that does not yet exist.\n\n"
        "To enable this trainer:\n"
        "  1. Complete OPD pilot and confirm improvement over the frozen baseline\n"
        "  2. Generate oracle-grounded proposals via Opus:\n"
        "       PYTHONPATH=src python -m co_scientist.d6_grant_proposal.build_oracle_sft \\\n"
        "           goal_domain=ai goal_name=02_foundational_rl\n"
        "  3. Train oracle SFT on those proposals (separate SFT script)\n"
        "  4. Set oracle_sft_checkpoint to the resulting checkpoint path\n"
        "  5. Implement the KL-anchor loss following D5's reference pattern\n\n"
        "See: projects/d6_grant_proposal/DECISIONS.md for the deferral rationale."
    )


# TODO: Implement KL anchor on top of OPD-grounded following D5's pattern.
# Key config additions vs OPD-grounded:
#   oracle_sft_checkpoint: str   — path to frozen π_oracle LoRA checkpoint
#   kl_beta: float = 0.01        — KL weight (D5 used 0.1 but 0.01 recommended for grant proposals)
#
# Advantage formula:
#   A_total[t] = clamp(
#       A_critique[t]                          # from OPD
#       + grounding_bonus[t]                   # from OPD-grounded
#       - kl_beta * (lp_theta[t] - lp_oracle[t]),  # KL anchor
#       ±opd_anchor_clip
#   )
#
# lp_oracle[t] = oracle SFT logprob at token t (frozen LoRA, no gradient)
#
# Build oracle SFT:
#   1. Prompt Opus: build_teacher_prompt(goal, oracle, COLD_START) × 30–50 times
#   2. Extract <solution> from each response → oracle_grounded_plans.jsonl
#   3. SFT on oracle_grounded_plans.jsonl using Tinker SFT API
#   4. Save frozen SFT LoRA checkpoint as π_oracle

if __name__ == "__main__":
    main()
